## PROG8245 Assignment 1: (Total Marks 100)
## Start on 16th of September- Due on 27th of September


- Name: Jun He
- ID: 8903073
- Kindly note that this assignment is to be solved by yourself, without the use of AI and chatbots.
- If chatbot usage is detected, the penalty that is discussed in Week 1 slides will apply.
- Each code block will have a Todo comment which explains the functionality, expected input, and expected output of the function.
- There are 10 marks in this assignment for assuring that the code couldn't be broken (no errors can be thrown, please consider mathematical and logical errors)
- There are 10 marks in this assignment for commenting and code readability.


### Part 1: Python Basics

#### Question 1:

In [4]:

def total_price(price, tax):
    # 3 marks
    # TODO: write the functionality of the code where
    #  you are taking as an input a price of an item and the
    #  tax in decimal (13% tax will be given as 0.13),
    #  you should return the taxedPrice of that item
    #  which will be the total price after tax a customer must pay
    # (The price of the item plus the applicable taxes)

    # s1: declare variable and calculate total price = after tax price + price
    taxedPrice = price + (price * tax)
    # s2 return 
    return taxedPrice

# user input two parameters
price = float(input("Please input the price of this product:"))
tax = 0.13
t_price = total_price(price,tax)
print(f"This product totally spends ${t_price:.2f} after tax")


This product totally spends $226.00 after tax


#### Question 2:

In [5]:
def divisible_by(x, y):
    # 3 marks
    # TODO: write a function that returns True if x is divisible by y,
    #  and returns False OTHERWISE (all other cases).

    # firstly, should check division cannot be 0
    if y == 0:
        return False
    # x is divisible by y %y will ==0
    return x % y == 0  

print(divisible_by(100,0)) # special condition division is 0
print(divisible_by(15,5))  # true
print(divisible_by(100,9)) # false
    

False
True
False


#### Question 3:

In [1]:
def basic_calculator(x, y, operator):
    # 5 marks
    # TODO: write the functionality of the code where you are
    #  coding a basic calculator that performs basic addition "+", subtraction "-",
    #  multiplication "*", division "/", modulus "%" and integer division "//"
    #  the function must apply the operator to x and y for example:
    #  basicCalculator(10, 15, "*") should apply 10*15 and save it to the result variable
    #  NOTE: YOU NEED TO HANDLE DIVISION ERRORS BY RETURNING A STRING WITH THE WORD "error"
    #  NOTE: YOU NEED TO HANDLE AN INVALID OPERATOR BY RETURNING A STRING HAVING THE WORD "invalid"

    #use try and except to deal with errors
    try:
        if operator == "+":
            result = x + y
        elif operator == "-":
            result = x - y
        elif operator == "*":
            result = x * y
        elif operator == "/":
            if y == 0:
                return "error"
            result = x / y
        elif operator == "%":
            if y == 0:
                return "error"
            result = x % y
        elif operator == "//":
            if y == 0:
                return "error"
            result = x // y
        else :
            return "invalid operator"

        return result
    except:
        return "error"
    
    # display different result
print(basic_calculator(66, 11, "+"))  
print(basic_calculator(66, 11, "-"))  
print(basic_calculator(66, 11, "*"))  
print(basic_calculator(66, 11, "/"))  
print(basic_calculator(66, 11, "%"))   
print(basic_calculator(66, 11, "//"))  

print(basic_calculator(66, 0, "/"))  
print(basic_calculator(66, 0, "%"))   
print(basic_calculator(66, 0, "//"))  


print(basic_calculator(66, 6, "^"))   
    

77
55
726
6.0
0
6
error
error
error
invalid operator


#### Question 4:

In [2]:
import re

def sum_of_even(numbers_list):
    try: # 3 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a list of numbers
    # returning the sum of even numbers in the list
    # NOTE: YOU NEED TO HANDLE ERRORS OF GIVING LIST OF STRINGS OR/AND
    #  STRINGS WITH NUMBERS by returning "invalid"
    # sum_of_even([1,2,3,4,5,6]) = 12

        even_total = 0
        for item in numbers_list:
            # firstly check if each element is valid or not
            if not  isinstance(item, int) : # or not (re.search(r'[\dA-Za-z]', item))
                return "invalid"
                
            if item % 2 == 0:
                even_total = even_total + item
        
        return even_total
    except:
        return "invalid" 
    
print(sum_of_even([1, 2, 3, 4, 5, 6]))  #  12
print(sum_of_even([8, 'abc9', 3, 6]))  # invalid
print(sum_of_even([5, 9, 11]))           #   all odd --0
print(sum_of_even([22, 4, 6, 8]))        #  all even -- 40

12
invalid
0
40


#### Question 5:

In [10]:
def reverse_string(input_string):
    # 3 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a string
    # returns the reverse of the string
    # reverse_string("hello") = "olleh"
    # NOTE: Numbers should be handled as strings ex: 123 returns "321"

    ##  negative steps to access elements starting from the end of the sequence
    return input_string[::-1]

# user input string  #any string, number, character
user_input = str(input("Please input something you want:"))
print("User input string is:"+user_input)
print("After reversing, the string changed into:"+reverse_string(user_input))





User input string is:helena-jun.01
After reversing, the string changed into:10.nuj-aneleh


#### Question 6:

In [27]:
def diamond_string(length):
    # 5 marks
    # TODO: write the functionality of the code where you are
    # taking as an input a POSITIVE ODD length
    # saves in a string the diamond as follows:
    # diamond_string(5)
    #   *
    #  ***
    # *****
    #  ***
    #   *
    # NOTE: The input must be positive odd, if not return empty string ""   

    # firstly, we should check if the length is POSITIVE ODD
    if length <= 0 or length % 2 == 0:
        return ""

    #declare diamond 
    diamond = []
    ## operator is used for integer (or floor) division, so if 5//2 == 2
    mid_num = length // 2
    
    ## Uses a loop to construct each line of the diamond. 
    # The number of stars increases until the middle of the diamond and then decreases
    for i in range(length):
        
        if i <= mid_num:
            stars = '*'*(2*i+1)
        else:
            stars = '*'*(2*(length-i-1)+1)
        spaces = ' ' *(abs(mid_num-i)) # mid - i get absolute value  0,1,2,1,0
        diamond.append(spaces+stars+spaces)
    return '\n'.join(diamond)

print(diamond_string(5))


  *  
 *** 
*****
 *** 
  *  


#### Question 7:

In [29]:
def longest_consecutive_subarray(number_array):
    # 8 marks
    # TODO: write the functionality of the code where you are
    # taking as an input an array of REAL NUMBERS
    # return the length of the longest subarray that could be
    # built using the input
    # longest_consecutive_subarray([100, 4, 200, 1, 3, 2]) = 4
    # Function should return 4 which represents in this case
    # the longest_consecutive_subarray that could be built [1,2,3,4]
    # You can't use Built in Sorting!
    # Note: - If any error exists in the input, "error" should be returned
    #       - The difference between any 2 consecuetive numbers is 1.


     # firstly,check if the input is a list of real numbers or int/float digital type
    if not isinstance(number_array, list) or not all(isinstance(x, (int, float)) for x in number_array):
        return "error"  
    

 # store the unique elements(use set) in the array
    number_set = set(number_array)
    # declare 
    longest_size = 0
    
    # Iterate through each number in the set
    for item in number_set:
        # checks if it’s the start of a sequence (i.e., num - 1 is not in the set).
        if item - 1 not in number_set:
            # if yes, assign item as current number and current_size = 1
            current_num = item
            current_size = 1
            
            # counts the length of the consecutive sequence starting from that number
            # also based on current number to find next consecutive number if exists number_set
            while current_num + 1 in number_set:
                current_num += 1
                current_size += 1
            
            # Update the longest streak found, find the max one
            longest_size = max(longest_size, current_size)
    
    return longest_size

# Test examples:
print(longest_consecutive_subarray([100, 4, 200, 1, 3, 2])) 
print(longest_consecutive_subarray([55, 15, 19, 12, 14, 16, 17, 13, 18,19]))  
print(longest_consecutive_subarray([98.0, 99.0, 97.0,100.00]))  
print(longest_consecutive_subarray("Helena str")) 

4
8
4
error


#### Question 8 (Challenging):

In [36]:
def can_be_segmented(input_string, word_dict):
    # 15 marks
    # TODO: Write the functionality of the code where you
    # are given as an input a string and a word_dict
    # Your target is to return True, if input_string can be segmented
    # (broken-down) into a sequence of one or more dictionary words
    # otherwise return False
    # Sample Input: can_be_segmented("applepenapple", {'apple','pen'}) ==> True
    # Sample Input: can_be_segmented("catsandog", {'cats','dog','sand','and','cat'}) ==> False
    # Hint: You can start by checking which prefix exist in the dictionary, and call the same function recursively
    # on the remaining string.

    # check input str length
    if len(input_string) == 0:
        return True
    #for loop every character or word 
    for i in range(1, len(input_string)+1):
        part_input = input_string[:i] # 1,2,3,4,5.....a ap app appl apple....
        # print(input_string[i:]) the rest of input string like: pplepenapple,plepenapple...
        # check if the part_input exists in the dic
        if part_input in word_dict:
            #  call the same function recursively
            if(can_be_segmented(input_string[i:],word_dict)):
                return True

    return False

print(can_be_segmented("applepenapple", {'apple', 'pen'})) 
print(can_be_segmented("catsandog", {'cats', 'dog', 'sand', 'and', 'cat'}))  
print(can_be_segmented("catsanddog", {'cats', 'dog', 'sand', 'and', 'cat'}))  

True
False
True


### Part 2: Numpy Basics: 
- In this Part of the assignment, you are <b>ONLY ALLOWED</b> to use Numpy and its functions. 
- You are not expected to use Loops.

In [37]:
import numpy as np

#### Question 9:

In [38]:
def no_zeros(array_input):
    # 3 marks
    ## TODO: This function should return True if 
    ## numpy array arrayInput does not contain any zero
    ## and will return False otherwise.
    ## Implement this function using ONLY numpy methods
    ## Sample input: np.array([1,2,3,4,5,6,0]) Sample Output: False
    ## Sample input: np.array([1,2,3,4,5,6]) Sample Output: True

 return np.all(array_input !=0)

print(no_zeros(np.array([1, 2, 3, 4, 5, 6, 0])))  # Outputs False
print(no_zeros(np.array([1, 2, 3, 4, 5, 6])))     # Outputs True



False
True


#### Question 10:

In [41]:
def two_dimensions(n):
    # 7 marks
    ## TODO: This function should create a 2d Array of shape n*n for any positive number
    ## Where the borders of the array are ones
    ## all other elements are zero
    ## Implement this function using ONLY numpy methods
    ## Sample input 3
    ## sample output [[1,1,1],[1,0,1],[1,1,1]]

    # firstly, check if the number is positive
    if n <= 0:
        return np.array({})
    
    # build a n*n array, each element is 0
    arry = np.zeros((n,n), dtype = int)
    
     ## Where the borders of the array are ones
     ## all other elements are zero
     # for above requirements, should set the first+last row and first+last column to 1
    arry[0, :] = 1 #first row
    arry[-1, :] =1 #last row
    arry[:, 0] =1 #first column
    arry[:, -1] =1 #last column
    return arry


print(two_dimensions(3))

    

    

[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### Question 11:

In [51]:
def random_generation(n,min,max):
    # 5 marks
    # TODO: Write a function that takes as an input
    # Dimension of 2d Array n, min and max
    # Generate an n*n array with random numbers between
    # min and max inclusive
    # Such that no element is duplicated
    # return numpy array
    # Implement this function using ONLY numpy methods
    # Sample Input: random_generation(3,0,12) --> [[4,2,6],[1,5,11],[10, 3,9]]

    # generate a array, the number from min to max+1
    array_2d = np.arange(min, max+1)
    print(array_2d)

    np.random.shuffle(array_2d)
    
    # After misordering randomly
    print(array_2d)

    return array_2d[:n*n].reshape(n,n)

print(random_generation(3,0,12))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[12  7 10  0  8  6 11  9  5  3  4  1  2]
[[12  7 10]
 [ 0  8  6]
 [11  9  5]]


#### Question 12:

In [52]:
def matrix_border_sum(matrix):
    # 8 marks
    # TODO: Write a function that takes as an input a matrix
    # and return the sum of all elements in the borders
    # Implement this function using ONLY numpy methods
    # Sample Input: np.array([[1,2,3],
    #                         [4,5,6],
    #                         [7,8,9]])
    # Output: matrix_border_sum(matrix) =  1+2+3+4+6+7+8+9 = 40

    # to fulfil this function should get the value that  top row, bottom row, left column (excluding the corners), 
    # and right column (excluding the corners) of the matrix and sums them up
    # declare border_sum
    border_sum = 0

    first_row = matrix[0,:]
    last_row  = matrix[-1,:]
    left_column = matrix[1:-1,0]  # 1:-1 Exclude the first and last rows
    right_column = matrix[1:-1,-1]
    border_sum = np.sum(first_row) + np.sum(last_row) + np.sum(left_column) + np.sum(right_column) 

    return border_sum

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Output
print(matrix_border_sum(matrix)) 

40


### Part 3: Pandas

In [1]:
import pandas as pd

#### Question 13 (12 marks): 
- Using RegularSeasonCompactResults.csv and Teams.csv apply the following functionalities

In [6]:
# Using RegularSeasonCompactResults.csv
# 1- Create a filter to show if there are any draw matches
# 2- Apply the filter to the dataframe
# 3- SHOW/PRINT the dataframe length or count (4 marks)
## TODO: Your code should be here

# draw matches means Wscore == Lscore
regular_Season_Compact_Results = pd.read_csv('RegularSeasonCompactResults.csv')
print(regular_Season_Compact_Results.head)
# so we can check each row if Wscore == Lscore
draw_condition = regular_Season_Compact_Results['Wscore'] == regular_Season_Compact_Results['Lscore']
# 2- Apply the filter to the dataframe
draw_matches = regular_Season_Compact_Results[draw_condition]
# 3- SHOW/PRINT the dataframe length or count (4 marks)
total_count_draw = len(draw_matches)
print(f"Totally draw matches are : {draw_matches if not draw_matches.empty else 'No draw matches found'}")




<bound method NDFrame.head of         Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0         1985      20   1228      81   1328      64    N      0
1         1985      25   1106      77   1354      70    H      0
2         1985      25   1112      63   1223      56    H      0
3         1985      25   1165      70   1432      54    H      0
4         1985      25   1192      86   1447      74    H      0
...        ...     ...    ...     ...    ...     ...  ...    ...
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0

[145289 rows x 8 columns]>
Totally draw matches are : No draw matches found


In [18]:
# Using RegularSeasonCompactResults.csv
matches_df = pd.read_csv('RegularSeasonCompactResults.csv')
# 1- Create a filter showing the entries where the winningteamID= 1400- (last two digits of your id)
my_id = 8903073
winning_team_ID= 1400- (my_id%100)
print(winning_team_ID)
winning_team_confition = matches_df['Wteam'] == winning_team_ID

# 2- Create another filter for the season of 2013
season_condition = matches_df['Season'] == 2013
season_condition1 = matches_df['Season'] == 1985

# 3- Apply the filter to the dataframe
final_result = matches_df[winning_team_confition & season_condition]
# 4- Show the resulted dataframe (4 marks)
# (Example: IF your id is 8000021, the winning team id = 1400-21= 1379)
# TODO: Your code should be here

final_result_other_season = matches_df[winning_team_confition & season_condition1]
print(f"{final_result if not final_result.empty else 'Empty result for winningteamID = 1327 and season = 2013'}")

print(f"Other condition like season = 1985,there result count is {len(final_result_other_season)} ")

1327
Empty result for winningteamID = 1327 and season = 2013
Other condition like season = 1985,there result count is 3 


In [22]:
# Using RegularSeasonCompactResults.csv & Teams.csv
# 1- Load and merge both dataframes

# 2- Where the merge is on WinningTeamId (RegularSeasonCompactResults) and TeamId (Teams.csv)
# 3- Name the dataframe: DFCombined
# 4- Show the top 3 rows (4 marks)
# TODO: Your code should be here


# load the data results
regular_season_compact_results = pd.read_csv('RegularSeasonCompactResults.csv')
teams_results = pd.read_csv('Teams.csv')
# merge the dataframes
DFCombined = pd.merge(regular_season_compact_results, teams_results, left_on='Wteam', right_on='Team_Id')
# display top 3 
print(f"Total march results: {len(DFCombined)}")
print("\n\n")
print(DFCombined.head(3))




Total march results: 145289



   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot  Team_Id  \
0    1985      20   1228      81   1328      64    N      0     1228   
1    1985      25   1106      77   1354      70    H      0     1106   
2    1985      25   1112      63   1223      56    H      0     1112   

    Team_Name  
0    Illinois  
1  Alabama St  
2     Arizona  
